name: eer-process
channels:
  - conda-forge
  - bioconda
dependencies:
  - pip
  - numpy
  - pandas
  - matplotlib
  - h5py
  - tqdm
  - seaborn
  - snakemake-minimal
  - xarray
  - ipykernel
  - jupyterlab
  - pip:
    - us
